### ISSUE TITLE
example of selectdaysfile=c() used in part 1

### ISSUE THREAD

**Issue by jwang-lilly** [xiangnandang/ggir_workshop#1]
Vincent, could you please provide a selectdaysfile as an example?

**Comment by vincentvanhees** [comment]
This only works if you are only interested in two specific dates of measurement. I implemented this for one specific study and did not envision that anyone else would use this function. I do not have an example selecdayfile, see documentation for required file structure.

**Comment by jwang-lilly** [comment]
Thanks,  Vincent, if it is only applicable for two specific dates, then it is probably not something of relevancy to my application.
